services:
  db:
    image: postgres:16-alpine
    container_name: temanpilah-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-teman_pilah}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-teman_pilah}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build: .
    container_name: temanpilah-app
    restart: unless-stopped
    ports:
      - "2000:2000"
    env_file:
      - .env
    volumes:
      - uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
  fe:
    build: /root/teman-pilah_fe
    container_name: temanpilah-fe
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=https://api.temanpilah.com
    depends_on:
      - app

volumes:
  pgdata:
  uploads:
